#!/bin/bash

hijacked_route=0
no_hijacked_route=0
Routers=($(docker ps | grep "rnode" | awk '{ print $1 }'))
RPKI=($(docker ps | grep "hnode" | grep "rpki" | awk '{ print $1 }'))

for router in ${Routers[@]}; do
  text=$(docker ps --format '{{.Names}}' -f "ID=$router")
  delimiter="-"
  string=$text$delimiter

  AS_info=()
  while [[ $string ]]; do
    AS_info+=( "${string%%"$delimiter"*}" )
    string=${string#*"$delimiter"}
  done
  echo "############### ${AS_info[0]} _ ${AS_info[1]} ###############"  
  docker exec $router /bin/bash -c "birdc show route all | grep -E '(^|\s)8.8.8.0/25($|\s)'" && let hijacked_route++ || let no_hijacked_route++ 
done
let no_hijacked_route--
echo "#Routers that have the hijacked route in its RIB: $hijacked_route"
echo "#Routers that do not have the hijacked route in its RIB: $no_hijacked_route"
echo "#ASes deployed RPKI: $(echo ${#RPKI[*]})"
for i in  ${RPKI[@]}; do
 echo "$(docker ps  --format '{{.Names}}' -f "ID=$i")"
done
