#!/bin/bash

RPKI=($(docker ps | grep "hnode" | awk '{ print $1 }'))

for host in ${RPKI[@]}; do
 
  text=$(docker ps --format '{{.Names}}' -f "ID=$host")
  delimiter="-"
  string=$text$delimiter
  AS_info=()
  while [[ $string ]]; do
    AS_info+=( "${string%%"$delimiter"*}" )
    string=${string#*"$delimiter"}
  done
  echo "################################################################"
  echo "#### ASN: ${AS_info[0]} ### AS IP: ${AS_info[2]} ####"
  echo "--------------- Ping ---------------"
  docker exec $host /bin/bash -c "ping -c 10 1.1.1.1"
  echo "--------------- Traceroute ---------------"
  docker exec $host /bin/bash -c "traceroute -m 25 1.1.1.1" 
done
